## Imports

In [2]:
import pandas as pd

## Importando os dados

In [3]:
performance = pd.read_excel('../Projeto Gerdau/Performance_Mensal.xls', header = 4)
performance

,Unnamed: 0,Jan\nJan,Fev\nFeb,Mar\nMar,Abr\nApr,Mai\nMay,Jun\nJun,Jul\nJul,Ago\nAug,Set\nSep,...,Jun\nJun.7,Jul\nJul.7,Ago\nAug.7,Set\nSep.7,Out\nOct.7,Nov\nNov.7,Dez\nDec,Jan\nJan.8,Fev\nFeb.8,Unnamed: 99
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,(%)
1,Produção / Production,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Aço Bruto / Crude Steel,2769.437,2574.894,2858.521,2913.622,2999.775,2836.535,2918.241,2976.770,2981.309,...,2138.728,2569.951,2705.136,2591.663,2784.028,2954.092,2886.223,3003.522,2845.184,-5.271744
3,Laminados / Rolled Products,2051.441,1942.836,2194.384,2211.587,2354.716,2284.417,2252.236,2257.548,2181.567,...,1551.981,1635.403,1823.467,1950.798,2125.078,1945.154,2090.405,2166.727,2050.248,-5.375804
4,Planos / Flat Products,1202.482,1144.078,1261.646,1233.065,1311.414,1285.362,1251.395,1270.671,1229.652,...,879.430,828.746,997.552,1096.683,1225.013,1081.750,1253.052,1293.969,1211.463,-6.376196
5,Longos / Long Products,848.959,798.758,932.738,978.522,1043.302,999.055,1000.841,986.877,951.915,...,672.551,806.657,825.915,854.115,900.065,863.404,837.353,872.758,838.785,-3.892603
6,Semiacabados P/ Vendas /\nSemifinished Product...,470.371,480.793,550.726,459.709,442.191,330.286,478.819,500.976,514.021,...,712.593,774.854,627.664,456.267,610.435,709.427,616.163,620.981,556.944,-10.312232
7,Placas / Slabs,394.660,417.568,435.452,386.750,346.131,266.185,367.807,395.244,423.621,...,606.447,701.892,581.795,412.477,544.627,691.755,572.893,596.597,537.701,-9.871991
8,"Blocos e Tarugos / Ingots, Blooms and Billets",75.711,63.225,115.274,72.959,96.060,64.101,111.012,105.732,90.400,...,106.146,72.962,45.869,43.790,65.808,17.672,43.270,24.384,19.243,-21.083497
9,Ferro-Gusa / Pig Iron,2178.041,1999.501,2157.547,2239.881,2240.067,2123.028,2213.095,2308.400,2244.132,...,1687.461,1990.333,2121.498,1990.157,2139.362,2325.076,2338.875,2429.518,2248.147,-7.465308
10,Vendas Internas / Domestic Sales (*),1905.819,1791.619,2062.865,2074.205,2193.013,2123.333,2095.949,2226.363,2111.765,...,1552.265,1729.179,1729.393,1870.601,1930.208,1833.292,1826.868,1923.804,1882.947,-2.123761
11,Laminados / Rolled Products,1852.831,1754.210,2006.225,2010.304,2129.468,2079.981,2043.645,2182.214,2054.041,...,1506.658,1697.612,1706.816,1848.460,1894.231,1795.493,1789.734,1894.333,1847.354,-2.479976
12,Planos / Flat Products,1088.146,1019.531,1141.455,1137.847,1228.297,1225.625,1147.725,1220.747,1183.966,...,823.812,916.575,967.263,1097.182,1101.980,1044.575,1089.852,1134.115,1090.464,-3.848904
13,Longos / Long Products,764.685,734.679,864.770,872.457,901.171,854.356,895.920,961.467,870.075,...,682.846,781.037,739.553,751.278,792.251,750.918,699.882,760.218,756.890,-0.437769
14,Semiacabados P/ Vendas /\nSemifinished Product...,52.988,37.409,56.640,63.901,63.545,43.352,52.304,44.149,57.724,...,45.607,31.567,22.577,22.141,35.977,37.799,37.134,29.471,35.593,20.772963
15,Placas / Slabs,31.043,19.015,28.417,38.753,23.967,15.375,21.042,20.405,26.662,...,17.623,10.445,9.447,7.374,11.839,13.493,11.115,8.502,13.147,54.634204
16,"Blocos e Tarugos / Ingots, Blooms and Billets",21.945,18.394,28.223,25.148,39.578,27.977,31.262,23.744,31.062,...,27.984,21.122,13.130,14.767,24.138,24.306,26.019,20.969,22.446,7.043731
17,Vendas Externas / Foreign Market (**),717.366,628.682,748.199,596.758,491.647,554.775,443.421,590.543,663.272,...,1003.287,925.363,841.084,627.786,791.537,660.048,920.535,565.529,657.043,16.182017
18,Laminados / Rolled Products,248.626,264.274,257.783,194.734,172.323,255.275,141.383,172.692,190.710,...,294.459,187.868,183.658,228.678,172.296,176.131,200.642,129.924,140.636,8.24482
19,Planos / Flat Products,178.471,159.736,178.049,98.464,87.111,159.878,68.841,70.028,79.065,...,178.054,117.153,95.121,111.997,92.981,65.705,75.552,56.711,79.576,40.318457
20,Longos / Long Products,70.155,104.538,79.734,96.270,85.212,95.397,72.542,102.664,111.645,...,116.405,70.715,88.537,116.681,79.315,110.426,125.090,73.213,61.060,-16.599511
21,Semiacabados P/ Vendas /\nSemifinished Product...,468.740,364.408,490.416,402.024,319.324,299.500,302.038,417.851,472.562,...,708.828,737.495,657.426,399.108,619.241,483.917,719.893,435.605,516.407,18.549374
22,Placas / Slabs,426.772,354.891,435.865,348.159,292.198,274.882,283.569,385.887,434.833,...,627.726,686.027,621.927,361.913,571.982,483.210,694.043,433.273,513.623,18.54489
23,"Blocos e Tarugos / Ingots, Blooms and Billets",41.968,9.517,54.551,53.865,27.126,24.618,18.469,31.964,37.729,...,81.102,51.468,35.499,37.195,47.259,0.707,25.850,2.332,2.784,19.382504
24,Comércio Exterior / Foreign Trade,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Exportações / Exports,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Laminados / Rolled Products,330.997,316.401,209.064,292.662,253.855,223.078,200.957,191.225,198.698,...,250.415,213.992,144.646,239.195,204.551,147.257,225.331,165.225,147.927,-10.46936
27,Planos / Flat Products,211.669,207.611,124.325,184.042,148.101,112.148,104.512,77.798,110.371,...,136.346,107.048,68.197,118.566,97.521,49.445,89.938,45.998,58.394,26.948998
28,Longos / Long Products,119.328,108.790,84.739,108.620,105.754,110.930,96.445,113.427,88.327,...,114.069,106.944,76.449,120.629,107.030,97.812,135.393,119.227,89.533,-24.905432
29,Semiacabados P/ Vendas /\nSemifinished Product...,601.860,498.926,509.507,524.697,353.768,319.883,267.459,391.060,433.970,...,825.402,661.315,696.090,517.030,637.745,367.123,540.996,365.924,617.645,68.790514
30,Placas / Slabs,547.595,453.566,471.095,462.410,321.500,271.330,235.836,355.317,382.671,...,790.035,617.556,628.769,477.622,630.907,364.995,537.564,363.490,617.598,69.907838
31,"Blocos e Tarugos / Ingots, Blooms and Billets",54.265,45.360,38.412,62.287,32.268,48.553,31.623,35.743,51.299,...,35.367,43.759,67.321,39.408,6.838,2.128,3.432,2.434,0.047,-98.069022
32,Total (Mil t / Thousand Tonnes),932.857,815.327,718.571,817.359,607.623,542.961,468.416,582.285,632.668,...,1075.817,875.307,840.736,756.225,842.296,514.380,766.327,531.149,765.572,44.135073
33,(US$ Milhões / US$ Millions),573.500,509.969,474.159,539.518,507.626,386.179,345.875,440.298,416.662,...,478.601,392.279,380.447,379.417,416.419,298.544,434.077,314.156,522.292,66.252435
34,Importações / Imports,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,Laminados / Rolled Products,277.653,294.211,271.067,329.344,264.948,238.591,381.225,336.011,362.242,...,186.547,142.661,128.563,140.065,139.086,197.651,203.169,275.421,235.588,-14.462586
36,Planos / Flat Products,140.752,155.913,140.296,188.103,148.586,133.037,222.136,251.937,225.803,...,129.525,109.865,90.773,105.951,95.531,131.340,130.090,200.906,133.079,-33.760565
37,Longos / Long Products,136.901,138.298,130.771,141.241,116.362,105.554,159.089,84.074,136.439,...,57.022,32.796,37.790,34.114,43.555,66.311,73.079,74.515,102.509,37.568275
38,Semiacabados P/ Vendas /\nSemifinished Product...,1.196,0.160,0.288,0.523,1.496,1.723,0.685,1.259,1.736,...,3.580,2.847,0.831,2.127,23.438,1.177,0.893,49.053,98.282,100.358796
39,Total (Mil t / Thousand Tonnes),278.849,294.371,271.355,329.867,266.444,240.314,381.910,337.270,363.978,...,190.127,145.508,129.394,142.192,162.524,198.828,204.062,324.474,333.870,2.895764
40,(US$ Milhões / US$ Millions),369.978,311.089,322.156,373.559,342.873,354.886,434.529,391.814,368.161,...,181.871,168.354,150.392,170.771,163.881,194.721,204.669,288.068,293.092,1.744033
41,Consumo Aparente / Apparent Consumption (***),2167.705,2069.840,2330.914,2402.633,2456.820,2358.624,2473.819,2559.039,2470.893,...,1742.923,1874.935,1858.691,2013.550,2072.571,2033.502,2032.196,2211.070,2125.371,-3.875906
42,Planos / Flat Products\n(Inclui Placas / Inclu...,1261.809,1195.402,1311.942,1367.514,1403.178,1375.828,1392.466,1493.575,1436.087,...,971.666,1037.157,1067.486,1211.337,1210.527,1190.791,1232.427,1344.807,1237.750,-7.960771
43,Longos / Long Products\n(Inclui Blocos e Tarug...,905.896,874.438,1018.972,1035.119,1053.642,982.796,1081.353,1065.464,1034.806,...,771.257,837.778,791.205,802.213,862.044,842.711,799.769,866.263,887.621,2.465533
44,(*) Exclui as vendas para dentro do parque. / ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,(**) Vendas faturadas pelas usinas. / Sales in...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,(***) Vendas Internas + Importação por Distrib...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,(***) Vendas Internas + Importação por Distrib...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,Nota / Note: Compreende os dados da laminadora...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,Fonte / Source: Aço Brasil / Min. da Economia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
## Verificando o número de colunas
performance.shape[1]

100

In [5]:
## Verificando quais são as colunas
performance.columns

Index(['Unnamed: 0', 'Jan\nJan', 'Fev\nFeb', 'Mar\nMar', 'Abr\nApr',
       'Mai\nMay', 'Jun\nJun', 'Jul\nJul', 'Ago\nAug', 'Set\nSep', 'Out\nOct',
       'Nov\nNov', 'Dez\nDez', 'Jan\nJan.1', 'Fev\nFeb.1', 'Mar\nMar.1',
       'Abr\nApr.1', 'Mai\nMay.1', 'Jun\nJun.1', 'Jul\nJul.1', 'Ago\nAug.1',
       'Set\nSep.1', 'Out\nOct.1', 'Nov\nNov.1', 'Dez\nDez.1', 'Jan\nJan.2',
       'Fev\nFeb.2', 'Mar\nMar.2', 'Abr\nApr.2', 'Mai\nMay.2', 'Jun\nJun.2',
       'Jul\nJul.2', 'Ago\nAug.2', 'Set\nSep.2', 'Out\nOct.2', 'Nov\nNov.2',
       'Dez\nDez.2', 'Jan\nJan.3', 'Fev\nFeb.3', 'Mar\nMar.3', 'Abr\nApr.3',
       'Mai\nMay.3', 'Jun\nJun.3', 'Jul\nJul.3', 'Ago\nAug.3', 'Set\nSep.3',
       'Out\nOct.3', 'Nov\nNov.3', 'Dez\nDez.3', 'Jan\nJan.4', 'Fev\nFeb.4',
       'Mar\nMar.4', 'Abr\nApr.4', 'Mai\nMay.4', 'Jun\nJun.4', 'Jul\nJul.4',
       'Ago\nAug.4', 'Set\nSep.4', 'Out\nOct.4', 'Nov\nNov.4', 'Dez\nDez.4',
       'Jan\nJan.5', 'Fev\nFeb.5', 'Mar\nMar.5', 'Abr\nApr.5', 'Mai\nMay.5',
       'Jun\nJun.5', 'Jul\nJul.5', 'Ago\nAug.5', 'Set\nSep.5', 'Out\nOct.5',
       'Nov\nNov.5', 'Dez\nDez.5', 'Jan\nJan.6', 'Fev\nFeb.6', 'Mar\nMar.6',
       'Abr\nApr.6', 'Mai\nMay.6', 'Jun\nJun.6', 'Jul\nJul.6', 'Ago\nAug.6',
       'Set\nSep.6', 'Out\nOct.6', 'Nov\nNov.6', 'Dez\nDez.6', 'Jan\nJan.7',
       'Fev\nFeb.7', 'Mar\nMar.7', 'Abr\nApr.7', 'Mai\nMay.7', 'Jun\nJun.7',
       'Jul\nJul.7', 'Ago\nAug.7', 'Set\nSep.7', 'Out\nOct.7', 'Nov\nNov.7',
       'Dez\nDec', 'Jan\nJan.8', 'Fev\nFeb.8', 'Unnamed: 99'],
      dtype='object')

### Arrumando a base de dados

In [6]:
## nomeando as colunas
def months_columns (mes_inicio, ano_inicio, n_coluna):
    nome_col = []
    lista_mes = ['Jan', 'Fev', 'Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez']
    i = 0 
    while(i<n_coluna):
        nome_temp = lista_mes[mes_inicio -1] +"_" +str(ano_inicio)
        nome_col.append(nome_temp)
        mes_inicio += 1
        if mes_inicio == 13:
            mes_inicio = 1
            ano_inicio += 1
        i +=1
    return nome_col

def fix_df(df, mes_inicio, ano_inicio, n_coluna=98):
    months_list = months_columns(mes_inicio, ano_inicio, n_coluna)
    new_columns = list()
    new_columns.append('especificacao')
    new_columns.extend(months_list)
    new_columns.append('pct')
    df.columns = new_columns
    return df

In [7]:
## Aplicando a função
temp = fix_df(df=performance, mes_inicio=1,ano_inicio=2013)

In [8]:
## Analisando a base de dados
temp

,especificacao,Jan_2013,Fev_2013,Mar_2013,Abr_2013,Mai_2013,Jun_2013,Jul_2013,Ago_2013,Set_2013,...,Jun_2020,Jul_2020,Ago_2020,Set_2020,Out_2020,Nov_2020,Dez_2020,Jan_2021,Fev_2021,pct
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,(%)
1,Produção / Production,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Aço Bruto / Crude Steel,2769.437,2574.894,2858.521,2913.622,2999.775,2836.535,2918.241,2976.770,2981.309,...,2138.728,2569.951,2705.136,2591.663,2784.028,2954.092,2886.223,3003.522,2845.184,-5.271744
3,Laminados / Rolled Products,2051.441,1942.836,2194.384,2211.587,2354.716,2284.417,2252.236,2257.548,2181.567,...,1551.981,1635.403,1823.467,1950.798,2125.078,1945.154,2090.405,2166.727,2050.248,-5.375804
4,Planos / Flat Products,1202.482,1144.078,1261.646,1233.065,1311.414,1285.362,1251.395,1270.671,1229.652,...,879.430,828.746,997.552,1096.683,1225.013,1081.750,1253.052,1293.969,1211.463,-6.376196
5,Longos / Long Products,848.959,798.758,932.738,978.522,1043.302,999.055,1000.841,986.877,951.915,...,672.551,806.657,825.915,854.115,900.065,863.404,837.353,872.758,838.785,-3.892603
6,Semiacabados P/ Vendas /\nSemifinished Product...,470.371,480.793,550.726,459.709,442.191,330.286,478.819,500.976,514.021,...,712.593,774.854,627.664,456.267,610.435,709.427,616.163,620.981,556.944,-10.312232
7,Placas / Slabs,394.660,417.568,435.452,386.750,346.131,266.185,367.807,395.244,423.621,...,606.447,701.892,581.795,412.477,544.627,691.755,572.893,596.597,537.701,-9.871991
8,"Blocos e Tarugos / Ingots, Blooms and Billets",75.711,63.225,115.274,72.959,96.060,64.101,111.012,105.732,90.400,...,106.146,72.962,45.869,43.790,65.808,17.672,43.270,24.384,19.243,-21.083497
9,Ferro-Gusa / Pig Iron,2178.041,1999.501,2157.547,2239.881,2240.067,2123.028,2213.095,2308.400,2244.132,...,1687.461,1990.333,2121.498,1990.157,2139.362,2325.076,2338.875,2429.518,2248.147,-7.465308
10,Vendas Internas / Domestic Sales (*),1905.819,1791.619,2062.865,2074.205,2193.013,2123.333,2095.949,2226.363,2111.765,...,1552.265,1729.179,1729.393,1870.601,1930.208,1833.292,1826.868,1923.804,1882.947,-2.123761
11,Laminados / Rolled Products,1852.831,1754.210,2006.225,2010.304,2129.468,2079.981,2043.645,2182.214,2054.041,...,1506.658,1697.612,1706.816,1848.460,1894.231,1795.493,1789.734,1894.333,1847.354,-2.479976
12,Planos / Flat Products,1088.146,1019.531,1141.455,1137.847,1228.297,1225.625,1147.725,1220.747,1183.966,...,823.812,916.575,967.263,1097.182,1101.980,1044.575,1089.852,1134.115,1090.464,-3.848904
13,Longos / Long Products,764.685,734.679,864.770,872.457,901.171,854.356,895.920,961.467,870.075,...,682.846,781.037,739.553,751.278,792.251,750.918,699.882,760.218,756.890,-0.437769
14,Semiacabados P/ Vendas /\nSemifinished Product...,52.988,37.409,56.640,63.901,63.545,43.352,52.304,44.149,57.724,...,45.607,31.567,22.577,22.141,35.977,37.799,37.134,29.471,35.593,20.772963
15,Placas / Slabs,31.043,19.015,28.417,38.753,23.967,15.375,21.042,20.405,26.662,...,17.623,10.445,9.447,7.374,11.839,13.493,11.115,8.502,13.147,54.634204
16,"Blocos e Tarugos / Ingots, Blooms and Billets",21.945,18.394,28.223,25.148,39.578,27.977,31.262,23.744,31.062,...,27.984,21.122,13.130,14.767,24.138,24.306,26.019,20.969,22.446,7.043731
17,Vendas Externas / Foreign Market (**),717.366,628.682,748.199,596.758,491.647,554.775,443.421,590.543,663.272,...,1003.287,925.363,841.084,627.786,791.537,660.048,920.535,565.529,657.043,16.182017
18,Laminados / Rolled Products,248.626,264.274,257.783,194.734,172.323,255.275,141.383,172.692,190.710,...,294.459,187.868,183.658,228.678,172.296,176.131,200.642,129.924,140.636,8.24482
19,Planos / Flat Products,178.471,159.736,178.049,98.464,87.111,159.878,68.841,70.028,79.065,...,178.054,117.153,95.121,111.997,92.981,65.705,75.552,56.711,79.576,40.318457
20,Longos / Long Products,70.155,104.538,79.734,96.270,85.212,95.397,72.542,102.664,111.645,...,116.405,70.715,88.537,116.681,79.315,110.426,125.090,73.213,61.060,-16.599511
21,Semiacabados P/ Vendas /\nSemifinished Product...,468.740,364.408,490.416,402.024,319.324,299.500,302.038,417.851,472.562,...,708.828,737.495,657.426,399.108,619.241,483.917,719.893,435.605,516.407,18.549374
22,Placas / Slabs,426.772,354.891,435.865,348.159,292.198,274.882,283.569,385.887,434.833,...,627.726,686.027,621.927,361.913,571.982,483.210,694.043,433.273,513.623,18.54489
23,"Blocos e Tarugos / Ingots, Blooms and Billets",41.968,9.517,54.551,53.865,27.126,24.618,18.469,31.964,37.729,...,81.102,51.468,35.499,37.195,47.259,0.707,25.850,2.332,2.784,19.382504
24,Comércio Exterior / Foreign Trade,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Exportações / Exports,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Laminados / Rolled Products,330.997,316.401,209.064,292.662,253.855,223.078,200.957,191.225,198.698,...,250.415,213.992,144.646,239.195,204.551,147.257,225.331,165.225,147.927,-10.46936
27,Planos / Flat Products,211.669,207.611,124.325,184.042,148.101,112.148,104.512,77.798,110.371,...,136.346,107.048,68.197,118.566,97.521,49.445,89.938,45.998,58.394,26.948998
28,Longos / Long Products,119.328,108.790,84.739,108.620,105.754,110.930,96.445,113.427,88.327,...,114.069,106.944,76.449,120.629,107.030,97.812,135.393,119.227,89.533,-24.905432
29,Semiacabados P/ Vendas /\nSemifinished Product...,601.860,498.926,509.507,524.697,353.768,319.883,267.459,391.060,433.970,...,825.402,661.315,696.090,517.030,637.745,367.123,540.996,365.924,617.645,68.790514
30,Placas / Slabs,547.595,453.566,471.095,462.410,321.500,271.330,235.836,355.317,382.671,...,790.035,617.556,628.769,477.622,630.907,364.995,537.564,363.490,617.598,69.907838
31,"Blocos e Tarugos / Ingots, Blooms and Billets",54.265,45.360,38.412,62.287,32.268,48.553,31.623,35.743,51.299,...,35.367,43.759,67.321,39.408,6.838,2.128,3.432,2.434,0.047,-98.069022
32,Total (Mil t / Thousand Tonnes),932.857,815.327,718.571,817.359,607.623,542.961,468.416,582.285,632.668,...,1075.817,875.307,840.736,756.225,842.296,514.380,766.327,531.149,765.572,44.135073
33,(US$ Milhões / US$ Millions),573.500,509.969,474.159,539.518,507.626,386.179,345.875,440.298,416.662,...,478.601,392.279,380.447,379.417,416.419,298.544,434.077,314.156,522.292,66.252435
34,Importações / Imports,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,Laminados / Rolled Products,277.653,294.211,271.067,329.344,264.948,238.591,381.225,336.011,362.242,...,186.547,142.661,128.563,140.065,139.086,197.651,203.169,275.421,235.588,-14.462586
36,Planos / Flat Products,140.752,155.913,140.296,188.103,148.586,133.037,222.136,251.937,225.803,...,129.525,109.865,90.773,105.951,95.531,131.340,130.090,200.906,133.079,-33.760565
37,Longos / Long Products,136.901,138.298,130.771,141.241,116.362,105.554,159.089,84.074,136.439,...,57.022,32.796,37.790,34.114,43.555,66.311,73.079,74.515,102.509,37.568275
38,Semiacabados P/ Vendas /\nSemifinished Product...,1.196,0.160,0.288,0.523,1.496,1.723,0.685,1.259,1.736,...,3.580,2.847,0.831,2.127,23.438,1.177,0.893,49.053,98.282,100.358796
39,Total (Mil t / Thousand Tonnes),278.849,294.371,271.355,329.867,266.444,240.314,381.910,337.270,363.978,...,190.127,145.508,129.394,142.192,162.524,198.828,204.062,324.474,333.870,2.895764
40,(US$ Milhões / US$ Millions),369.978,311.089,322.156,373.559,342.873,354.886,434.529,391.814,368.161,...,181.871,168.354,150.392,170.771,163.881,194.721,204.669,288.068,293.092,1.744033
41,Consumo Aparente / Apparent Consumption (***),2167.705,2069.840,2330.914,2402.633,2456.820,2358.624,2473.819,2559.039,2470.893,...,1742.923,1874.935,1858.691,2013.550,2072.571,2033.502,2032.196,2211.070,2125.371,-3.875906
42,Planos / Flat Products\n(Inclui Placas / Inclu...,1261.809,1195.402,1311.942,1367.514,1403.178,1375.828,1392.466,1493.575,1436.087,...,971.666,1037.157,1067.486,1211.337,1210.527,1190.791,1232.427,1344.807,1237.750,-7.960771
43,Longos / Long Products\n(Inclui Blocos e Tarug...,905.896,874.438,1018.972,1035.119,1053.642,982.796,1081.353,1065.464,1034.806,...,771.257,837.778,791.205,802.213,862.044,842.711,799.769,866.263,887.621,2.465533
44,(*) Exclui as vendas para dentro do parque. / ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,(**) Vendas faturadas pelas usinas. / Sales in...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,(***) Vendas Internas + Importação por Distrib...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,(***) Vendas Internas + Importação por Distrib...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,Nota / Note: Compreende os dados da laminadora...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,Fonte / Source: Aço Brasil / Min. da Economia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
## Removendo as linhas que não serão utilizadas e estão com valores nulos.
temp2 =pd.DataFrame(temp.drop([0,44,45,46,47,48,49], axis=0))
temp2

,especificacao,Jan_2013,Fev_2013,Mar_2013,Abr_2013,Mai_2013,Jun_2013,Jul_2013,Ago_2013,Set_2013,...,Jun_2020,Jul_2020,Ago_2020,Set_2020,Out_2020,Nov_2020,Dez_2020,Jan_2021,Fev_2021,pct
1,Produção / Production,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Aço Bruto / Crude Steel,2769.437,2574.894,2858.521,2913.622,2999.775,2836.535,2918.241,2976.770,2981.309,...,2138.728,2569.951,2705.136,2591.663,2784.028,2954.092,2886.223,3003.522,2845.184,-5.271744
3,Laminados / Rolled Products,2051.441,1942.836,2194.384,2211.587,2354.716,2284.417,2252.236,2257.548,2181.567,...,1551.981,1635.403,1823.467,1950.798,2125.078,1945.154,2090.405,2166.727,2050.248,-5.375804
4,Planos / Flat Products,1202.482,1144.078,1261.646,1233.065,1311.414,1285.362,1251.395,1270.671,1229.652,...,879.430,828.746,997.552,1096.683,1225.013,1081.750,1253.052,1293.969,1211.463,-6.376196
5,Longos / Long Products,848.959,798.758,932.738,978.522,1043.302,999.055,1000.841,986.877,951.915,...,672.551,806.657,825.915,854.115,900.065,863.404,837.353,872.758,838.785,-3.892603
6,Semiacabados P/ Vendas /\nSemifinished Product...,470.371,480.793,550.726,459.709,442.191,330.286,478.819,500.976,514.021,...,712.593,774.854,627.664,456.267,610.435,709.427,616.163,620.981,556.944,-10.312232
7,Placas / Slabs,394.660,417.568,435.452,386.750,346.131,266.185,367.807,395.244,423.621,...,606.447,701.892,581.795,412.477,544.627,691.755,572.893,596.597,537.701,-9.871991
8,"Blocos e Tarugos / Ingots, Blooms and Billets",75.711,63.225,115.274,72.959,96.060,64.101,111.012,105.732,90.400,...,106.146,72.962,45.869,43.790,65.808,17.672,43.270,24.384,19.243,-21.083497
9,Ferro-Gusa / Pig Iron,2178.041,1999.501,2157.547,2239.881,2240.067,2123.028,2213.095,2308.400,2244.132,...,1687.461,1990.333,2121.498,1990.157,2139.362,2325.076,2338.875,2429.518,2248.147,-7.465308
10,Vendas Internas / Domestic Sales (*),1905.819,1791.619,2062.865,2074.205,2193.013,2123.333,2095.949,2226.363,2111.765,...,1552.265,1729.179,1729.393,1870.601,1930.208,1833.292,1826.868,1923.804,1882.947,-2.123761
11,Laminados / Rolled Products,1852.831,1754.210,2006.225,2010.304,2129.468,2079.981,2043.645,2182.214,2054.041,...,1506.658,1697.612,1706.816,1848.460,1894.231,1795.493,1789.734,1894.333,1847.354,-2.479976
12,Planos / Flat Products,1088.146,1019.531,1141.455,1137.847,1228.297,1225.625,1147.725,1220.747,1183.966,...,823.812,916.575,967.263,1097.182,1101.980,1044.575,1089.852,1134.115,1090.464,-3.848904
13,Longos / Long Products,764.685,734.679,864.770,872.457,901.171,854.356,895.920,961.467,870.075,...,682.846,781.037,739.553,751.278,792.251,750.918,699.882,760.218,756.890,-0.437769
14,Semiacabados P/ Vendas /\nSemifinished Product...,52.988,37.409,56.640,63.901,63.545,43.352,52.304,44.149,57.724,...,45.607,31.567,22.577,22.141,35.977,37.799,37.134,29.471,35.593,20.772963
15,Placas / Slabs,31.043,19.015,28.417,38.753,23.967,15.375,21.042,20.405,26.662,...,17.623,10.445,9.447,7.374,11.839,13.493,11.115,8.502,13.147,54.634204
16,"Blocos e Tarugos / Ingots, Blooms and Billets",21.945,18.394,28.223,25.148,39.578,27.977,31.262,23.744,31.062,...,27.984,21.122,13.130,14.767,24.138,24.306,26.019,20.969,22.446,7.043731
17,Vendas Externas / Foreign Market (**),717.366,628.682,748.199,596.758,491.647,554.775,443.421,590.543,663.272,...,1003.287,925.363,841.084,627.786,791.537,660.048,920.535,565.529,657.043,16.182017
18,Laminados / Rolled Products,248.626,264.274,257.783,194.734,172.323,255.275,141.383,172.692,190.710,...,294.459,187.868,183.658,228.678,172.296,176.131,200.642,129.924,140.636,8.24482
19,Planos / Flat Products,178.471,159.736,178.049,98.464,87.111,159.878,68.841,70.028,79.065,...,178.054,117.153,95.121,111.997,92.981,65.705,75.552,56.711,79.576,40.318457
20,Longos / Long Products,70.155,104.538,79.734,96.270,85.212,95.397,72.542,102.664,111.645,...,116.405,70.715,88.537,116.681,79.315,110.426,125.090,73.213,61.060,-16.599511
21,Semiacabados P/ Vendas /\nSemifinished Product...,468.740,364.408,490.416,402.024,319.324,299.500,302.038,417.851,472.562,...,708.828,737.495,657.426,399.108,619.241,483.917,719.893,435.605,516.407,18.549374
22,Placas / Slabs,426.772,354.891,435.865,348.159,292.198,274.882,283.569,385.887,434.833,...,627.726,686.027,621.927,361.913,571.982,483.210,694.043,433.273,513.623,18.54489
23,"Blocos e Tarugos / Ingots, Blooms and Billets",41.968,9.517,54.551,53.865,27.126,24.618,18.469,31.964,37.729,...,81.102,51.468,35.499,37.195,47.259,0.707,25.850,2.332,2.784,19.382504
24,Comércio Exterior / Foreign Trade,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Exportações / Exports,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Laminados / Rolled Products,330.997,316.401,209.064,292.662,253.855,223.078,200.957,191.225,198.698,...,250.415,213.992,144.646,239.195,204.551,147.257,225.331,165.225,147.927,-10.46936
27,Planos / Flat Products,211.669,207.611,124.325,184.042,148.101,112.148,104.512,77.798,110.371,...,136.346,107.048,68.197,118.566,97.521,49.445,89.938,45.998,58.394,26.948998
28,Longos / Long Products,119.328,108.790,84.739,108.620,105.754,110.930,96.445,113.427,88.327,...,114.069,106.944,76.449,120.629,107.030,97.812,135.393,119.227,89.533,-24.905432
29,Semiacabados P/ Vendas /\nSemifinished Product...,601.860,498.926,509.507,524.697,353.768,319.883,267.459,391.060,433.970,...,825.402,661.315,696.090,517.030,637.745,367.123,540.996,365.924,617.645,68.790514
30,Placas / Slabs,547.595,453.566,471.095,462.410,321.500,271.330,235.836,355.317,382.671,...,790.035,617.556,628.769,477.622,630.907,364.995,537.564,363.490,617.598,69.907838
31,"Blocos e Tarugos / Ingots, Blooms and Billets",54.265,45.360,38.412,62.287,32.268,48.553,31.623,35.743,51.299,...,35.367,43.759,67.321,39.408,6.838,2.128,3.432,2.434,0.047,-98.069022
32,Total (Mil t / Thousand Tonnes),932.857,815.327,718.571,817.359,607.623,542.961,468.416,582.285,632.668,...,1075.817,875.307,840.736,756.225,842.296,514.380,766.327,531.149,765.572,44.135073
33,(US$ Milhões / US$ Millions),573.500,509.969,474.159,539.518,507.626,386.179,345.875,440.298,416.662,...,478.601,392.279,380.447,379.417,416.419,298.544,434.077,314.156,522.292,66.252435
34,Importações / Imports,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,Laminados / Rolled Products,277.653,294.211,271.067,329.344,264.948,238.591,381.225,336.011,362.242,...,186.547,142.661,128.563,140.065,139.086,197.651,203.169,275.421,235.588,-14.462586
36,Planos / Flat Products,140.752,155.913,140.296,188.103,148.586,133.037,222.136,251.937,225.803,...,129.525,109.865,90.773,105.951,95.531,131.340,130.090,200.906,133.079,-33.760565
37,Longos / Long Products,136.901,138.298,130.771,141.241,116.362,105.554,159.089,84.074,136.439,...,57.022,32.796,37.790,34.114,43.555,66.311,73.079,74.515,102.509,37.568275
38,Semiacabados P/ Vendas /\nSemifinished Product...,1.196,0.160,0.288,0.523,1.496,1.723,0.685,1.259,1.736,...,3.580,2.847,0.831,2.127,23.438,1.177,0.893,49.053,98.282,100.358796
39,Total (Mil t / Thousand Tonnes),278.849,294.371,271.355,329.867,266.444,240.314,381.910,337.270,363.978,...,190.127,145.508,129.394,142.192,162.524,198.828,204.062,324.474,333.870,2.895764
40,(US$ Milhões / US$ Millions),369.978,311.089,322.156,373.559,342.873,354.886,434.529,391.814,368.161,...,181.871,168.354,150.392,170.771,163.881,194.721,204.669,288.068,293.092,1.744033
41,Consumo Aparente / Apparent Consumption (***),2167.705,2069.840,2330.914,2402.633,2456.820,2358.624,2473.819,2559.039,2470.893,...,1742.923,1874.935,1858.691,2013.550,2072.571,2033.502,2032.196,2211.070,2125.371,-3.875906
42,Planos / Flat Products\n(Inclui Placas / Inclu...,1261.809,1195.402,1311.942,1367.514,1403.178,1375.828,1392.466,1493.575,1436.087,...,971.666,1037.157,1067.486,1211.337,1210.527,1190.791,1232.427,1344.807,1237.750,-7.960771
43,Longos / Long Products\n(Inclui Blocos e Tarug...,905.896,874.438,1018.972,1035.119,1053.642,982.796,1081.353,1065.464,1034.806,...,771.257,837.778,791.205,802.213,862.044,842.711,799.769,866.263,887.621,2.465533

-Produção: Aço Bruto + Laminados (Planos + Longos) + Semiacabado p/ venda (Placas + Blocos e Tarugos) + Ferro-Gusa.

-Venda internas: Laminados (Planos + Longos) + Semiacabado p/ venda (Placas + Blocos e Tarugos).

-Venda ezxterna: Laminados (Planos + Longos) + Semiacabado p/ venda (Placas + Blocos e Tarugos).

-Comércio Exterior / Exportação: Laminados (Planos + Longos) + Semiacabado p/ venda (Placas + Blocos e Tarugos).

-Importações: Laminados (Planos + Longos) + Semiacabado p/ venda

-Laminados: Planos + Longos.

-Semiacabado p/ venda: Placas + Blocos e Tarugos.

-Consumno aparente: Planos + Longos

Considerando as linhas cima como sendo o resultado da somatória das demais linhas. As linhas produção, venda interna, venda externa, comércio exterior, exportações, importações, e consumno aparente, laminados, semiacabados p/venda serão removidos com exceção da linha semiacado p/ Venda pois esta não apresenta uma subcategoria.

A linhas Total e Milhões US$ das categorias de importação e exportação serão incluídas em outro DataFrame.

In [10]:
temp3 =pd.DataFrame(temp2.drop([1,3,6,10,11,14,17,18,21,24,25,26,29,32,33,34,35,39,40,41,], axis=0))
temp3

,especificacao,Jan_2013,Fev_2013,Mar_2013,Abr_2013,Mai_2013,Jun_2013,Jul_2013,Ago_2013,Set_2013,...,Jun_2020,Jul_2020,Ago_2020,Set_2020,Out_2020,Nov_2020,Dez_2020,Jan_2021,Fev_2021,pct
2,Aço Bruto / Crude Steel,2769.437,2574.894,2858.521,2913.622,2999.775,2836.535,2918.241,2976.770,2981.309,...,2138.728,2569.951,2705.136,2591.663,2784.028,2954.092,2886.223,3003.522,2845.184,-5.271744
4,Planos / Flat Products,1202.482,1144.078,1261.646,1233.065,1311.414,1285.362,1251.395,1270.671,1229.652,...,879.430,828.746,997.552,1096.683,1225.013,1081.750,1253.052,1293.969,1211.463,-6.376196
5,Longos / Long Products,848.959,798.758,932.738,978.522,1043.302,999.055,1000.841,986.877,951.915,...,672.551,806.657,825.915,854.115,900.065,863.404,837.353,872.758,838.785,-3.892603
7,Placas / Slabs,394.660,417.568,435.452,386.750,346.131,266.185,367.807,395.244,423.621,...,606.447,701.892,581.795,412.477,544.627,691.755,572.893,596.597,537.701,-9.871991
8,"Blocos e Tarugos / Ingots, Blooms and Billets",75.711,63.225,115.274,72.959,96.060,64.101,111.012,105.732,90.400,...,106.146,72.962,45.869,43.790,65.808,17.672,43.270,24.384,19.243,-21.083497
9,Ferro-Gusa / Pig Iron,2178.041,1999.501,2157.547,2239.881,2240.067,2123.028,2213.095,2308.400,2244.132,...,1687.461,1990.333,2121.498,1990.157,2139.362,2325.076,2338.875,2429.518,2248.147,-7.465308
12,Planos / Flat Products,1088.146,1019.531,1141.455,1137.847,1228.297,1225.625,1147.725,1220.747,1183.966,...,823.812,916.575,967.263,1097.182,1101.980,1044.575,1089.852,1134.115,1090.464,-3.848904
13,Longos / Long Products,764.685,734.679,864.770,872.457,901.171,854.356,895.920,961.467,870.075,...,682.846,781.037,739.553,751.278,792.251,750.918,699.882,760.218,756.890,-0.437769
15,Placas / Slabs,31.043,19.015,28.417,38.753,23.967,15.375,21.042,20.405,26.662,...,17.623,10.445,9.447,7.374,11.839,13.493,11.115,8.502,13.147,54.634204
16,"Blocos e Tarugos / Ingots, Blooms and Billets",21.945,18.394,28.223,25.148,39.578,27.977,31.262,23.744,31.062,...,27.984,21.122,13.130,14.767,24.138,24.306,26.019,20.969,22.446,7.043731
19,Planos / Flat Products,178.471,159.736,178.049,98.464,87.111,159.878,68.841,70.028,79.065,...,178.054,117.153,95.121,111.997,92.981,65.705,75.552,56.711,79.576,40.318457
20,Longos / Long Products,70.155,104.538,79.734,96.270,85.212,95.397,72.542,102.664,111.645,...,116.405,70.715,88.537,116.681,79.315,110.426,125.090,73.213,61.060,-16.599511
22,Placas / Slabs,426.772,354.891,435.865,348.159,292.198,274.882,283.569,385.887,434.833,...,627.726,686.027,621.927,361.913,571.982,483.210,694.043,433.273,513.623,18.54489
23,"Blocos e Tarugos / Ingots, Blooms and Billets",41.968,9.517,54.551,53.865,27.126,24.618,18.469,31.964,37.729,...,81.102,51.468,35.499,37.195,47.259,0.707,25.850,2.332,2.784,19.382504
27,Planos / Flat Products,211.669,207.611,124.325,184.042,148.101,112.148,104.512,77.798,110.371,...,136.346,107.048,68.197,118.566,97.521,49.445,89.938,45.998,58.394,26.948998
28,Longos / Long Products,119.328,108.790,84.739,108.620,105.754,110.930,96.445,113.427,88.327,...,114.069,106.944,76.449,120.629,107.030,97.812,135.393,119.227,89.533,-24.905432
30,Placas / Slabs,547.595,453.566,471.095,462.410,321.500,271.330,235.836,355.317,382.671,...,790.035,617.556,628.769,477.622,630.907,364.995,537.564,363.490,617.598,69.907838
31,"Blocos e Tarugos / Ingots, Blooms and Billets",54.265,45.360,38.412,62.287,32.268,48.553,31.623,35.743,51.299,...,35.367,43.759,67.321,39.408,6.838,2.128,3.432,2.434,0.047,-98.069022
36,Planos / Flat Products,140.752,155.913,140.296,188.103,148.586,133.037,222.136,251.937,225.803,...,129.525,109.865,90.773,105.951,95.531,131.340,130.090,200.906,133.079,-33.760565
37,Longos / Long Products,136.901,138.298,130.771,141.241,116.362,105.554,159.089,84.074,136.439,...,57.022,32.796,37.790,34.114,43.555,66.311,73.079,74.515,102.509,37.568275
38,Semiacabados P/ Vendas /\nSemifinished Product...,1.196,0.160,0.288,0.523,1.496,1.723,0.685,1.259,1.736,...,3.580,2.847,0.831,2.127,23.438,1.177,0.893,49.053,98.282,100.358796
42,Planos / Flat Products\n(Inclui Placas / Inclu...,1261.809,1195.402,1311.942,1367.514,1403.178,1375.828,1392.466,1493.575,1436.087,...,971.666,1037.157,1067.486,1211.337,1210.527,1190.791,1232.427,1344.807,1237.750,-7.960771
43,Longos / Long Products\n(Inclui Blocos e Tarug...,905.896,874.438,1018.972,1035.119,1053.642,982.796,1081.353,1065.464,1034.806,...,771.257,837.778,791.205,802.213,862.044,842.711,799.769,866.263,887.621,2.465533

In [11]:
## Resete index
temp3.reset_index(drop=True, inplace = True)

In [12]:
## Renomeando as linhas da coluna 'especificação' para identificar a categoria que elas pertencem, sendo:
## Produção
## Venda interna - Vinterna
## Venda externa - Vexterna
## Comércio Exterior/Exportação - Cexterior
## Importação
## Consumo Aparente - Caparente
value = ["Producao.Aco Bruto", "Producao.Planos","Producao.Longos","Producao.Placas","Producao.Blocos","Producao.Ferro-Gusa","Vinterna.Planos", 
         "Vinterna.Longos","Vinterna.Placas","Vinterna.Blocos","Vexterna.Planos","Vexterna.Longos","Vexterna.Placas","Vexterna.Blocos", 
         "Cexterior.Planos","Cexterior.Longos","Cexterior.Placas","Cexterior.Blocos","Importacao.Planos","Importacao.Longos", 
         "Importacao.Semiacabados p/ Venda","Caparente.Planos", "Caparente.Longos"]
temp3.iloc[:,[0]] = value
temp3

,especificacao,Jan_2013,Fev_2013,Mar_2013,Abr_2013,Mai_2013,Jun_2013,Jul_2013,Ago_2013,Set_2013,...,Jun_2020,Jul_2020,Ago_2020,Set_2020,Out_2020,Nov_2020,Dez_2020,Jan_2021,Fev_2021,pct
0,Producao.Aco Bruto,2769.437,2574.894,2858.521,2913.622,2999.775,2836.535,2918.241,2976.770,2981.309,...,2138.728,2569.951,2705.136,2591.663,2784.028,2954.092,2886.223,3003.522,2845.184,-5.271744
1,Producao.Planos,1202.482,1144.078,1261.646,1233.065,1311.414,1285.362,1251.395,1270.671,1229.652,...,879.430,828.746,997.552,1096.683,1225.013,1081.750,1253.052,1293.969,1211.463,-6.376196
2,Producao.Longos,848.959,798.758,932.738,978.522,1043.302,999.055,1000.841,986.877,951.915,...,672.551,806.657,825.915,854.115,900.065,863.404,837.353,872.758,838.785,-3.892603
3,Producao.Placas,394.660,417.568,435.452,386.750,346.131,266.185,367.807,395.244,423.621,...,606.447,701.892,581.795,412.477,544.627,691.755,572.893,596.597,537.701,-9.871991
4,Producao.Blocos,75.711,63.225,115.274,72.959,96.060,64.101,111.012,105.732,90.400,...,106.146,72.962,45.869,43.790,65.808,17.672,43.270,24.384,19.243,-21.083497
5,Producao.Ferro-Gusa,2178.041,1999.501,2157.547,2239.881,2240.067,2123.028,2213.095,2308.400,2244.132,...,1687.461,1990.333,2121.498,1990.157,2139.362,2325.076,2338.875,2429.518,2248.147,-7.465308
6,Vinterna.Planos,1088.146,1019.531,1141.455,1137.847,1228.297,1225.625,1147.725,1220.747,1183.966,...,823.812,916.575,967.263,1097.182,1101.980,1044.575,1089.852,1134.115,1090.464,-3.848904
7,Vinterna.Longos,764.685,734.679,864.770,872.457,901.171,854.356,895.920,961.467,870.075,...,682.846,781.037,739.553,751.278,792.251,750.918,699.882,760.218,756.890,-0.437769
8,Vinterna.Placas,31.043,19.015,28.417,38.753,23.967,15.375,21.042,20.405,26.662,...,17.623,10.445,9.447,7.374,11.839,13.493,11.115,8.502,13.147,54.634204
9,Vinterna.Blocos,21.945,18.394,28.223,25.148,39.578,27.977,31.262,23.744,31.062,...,27.984,21.122,13.130,14.767,24.138,24.306,26.019,20.969,22.446,7.043731
10,Vexterna.Planos,178.471,159.736,178.049,98.464,87.111,159.878,68.841,70.028,79.065,...,178.054,117.153,95.121,111.997,92.981,65.705,75.552,56.711,79.576,40.318457
11,Vexterna.Longos,70.155,104.538,79.734,96.270,85.212,95.397,72.542,102.664,111.645,...,116.405,70.715,88.537,116.681,79.315,110.426,125.090,73.213,61.060,-16.599511
12,Vexterna.Placas,426.772,354.891,435.865,348.159,292.198,274.882,283.569,385.887,434.833,...,627.726,686.027,621.927,361.913,571.982,483.210,694.043,433.273,513.623,18.54489
13,Vexterna.Blocos,41.968,9.517,54.551,53.865,27.126,24.618,18.469,31.964,37.729,...,81.102,51.468,35.499,37.195,47.259,0.707,25.850,2.332,2.784,19.382504
14,Cexterior.Planos,211.669,207.611,124.325,184.042,148.101,112.148,104.512,77.798,110.371,...,136.346,107.048,68.197,118.566,97.521,49.445,89.938,45.998,58.394,26.948998
15,Cexterior.Longos,119.328,108.790,84.739,108.620,105.754,110.930,96.445,113.427,88.327,...,114.069,106.944,76.449,120.629,107.030,97.812,135.393,119.227,89.533,-24.905432
16,Cexterior.Placas,547.595,453.566,471.095,462.410,321.500,271.330,235.836,355.317,382.671,...,790.035,617.556,628.769,477.622,630.907,364.995,537.564,363.490,617.598,69.907838
17,Cexterior.Blocos,54.265,45.360,38.412,62.287,32.268,48.553,31.623,35.743,51.299,...,35.367,43.759,67.321,39.408,6.838,2.128,3.432,2.434,0.047,-98.069022
18,Importacao.Planos,140.752,155.913,140.296,188.103,148.586,133.037,222.136,251.937,225.803,...,129.525,109.865,90.773,105.951,95.531,131.340,130.090,200.906,133.079,-33.760565
19,Importacao.Longos,136.901,138.298,130.771,141.241,116.362,105.554,159.089,84.074,136.439,...,57.022,32.796,37.790,34.114,43.555,66.311,73.079,74.515,102.509,37.568275
20,Importacao.Semiacabados p/ Venda,1.196,0.160,0.288,0.523,1.496,1.723,0.685,1.259,1.736,...,3.580,2.847,0.831,2.127,23.438,1.177,0.893,49.053,98.282,100.358796
21,Caparente.Planos,1261.809,1195.402,1311.942,1367.514,1403.178,1375.828,1392.466,1493.575,1436.087,...,971.666,1037.157,1067.486,1211.337,1210.527,1190.791,1232.427,1344.807,1237.750,-7.960771
22,Caparente.Longos,905.896,874.438,1018.972,1035.119,1053.642,982.796,1081.353,1065.464,1034.806,...,771.257,837.778,791.205,802.213,862.044,842.711,799.769,866.263,887.621,2.465533

In [13]:
## Tranformando os dados do formato largo para o formato longo.
lista_ano = temp3.columns
lista_ano = lista_ano[1:99]
df = pd.melt(temp3, id_vars=['especificacao'], value_vars=lista_ano)
df.rename(columns = {'variable':'periodo', 'value':'quantidade'}, inplace = True)
df

                         especificacao   periodo  quantidade
0                   Producao.Aco Bruto  Jan_2013    2769.437
1                      Producao.Planos  Jan_2013    1202.482
2                      Producao.Longos  Jan_2013     848.959
3                      Producao.Placas  Jan_2013     394.660
4                      Producao.Blocos  Jan_2013      75.711
...                                ...       ...         ...
2249                 Importacao.Planos  Fev_2021     133.079
2250                 Importacao.Longos  Fev_2021     102.509
2251  Importacao.Semiacabados p/ Venda  Fev_2021      98.282
2252                  Caparente.Planos  Fev_2021    1237.750
2253                  Caparente.Longos  Fev_2021     887.621

[2254 rows x 3 columns]

In [14]:
##Criando uma coluna para ano e uma coluna para mês
mes = []
ano = []
for per in df['periodo']:
    periodo = per.split('_')
    mes.append(periodo[0])
    ano.append(periodo[1])   
df['ano'] = ano
df['mes'] = mes
df

                         especificacao   periodo  quantidade   ano  mes
0                   Producao.Aco Bruto  Jan_2013    2769.437  2013  Jan
1                      Producao.Planos  Jan_2013    1202.482  2013  Jan
2                      Producao.Longos  Jan_2013     848.959  2013  Jan
3                      Producao.Placas  Jan_2013     394.660  2013  Jan
4                      Producao.Blocos  Jan_2013      75.711  2013  Jan
...                                ...       ...         ...   ...  ...
2249                 Importacao.Planos  Fev_2021     133.079  2021  Fev
2250                 Importacao.Longos  Fev_2021     102.509  2021  Fev
2251  Importacao.Semiacabados p/ Venda  Fev_2021      98.282  2021  Fev
2252                  Caparente.Planos  Fev_2021    1237.750  2021  Fev
2253                  Caparente.Longos  Fev_2021     887.621  2021  Fev

[2254 rows x 5 columns]

In [15]:
##Criando uma coluna para subcategoria e uma coluna para a categoria
categoria = []
subcategoria = []
for esp in df['especificacao']:
    total = esp.split('.')
    categoria.append(total[0])
    subcategoria.append(total[1])   
df['categoria'] = categoria
df['subcategoria'] = subcategoria
df

,especificacao,periodo,quantidade,ano,mes,categoria,subcategoria
0,Producao.Aco Bruto,Jan_2013,2769.437,2013,Jan,Producao,Aco Bruto
1,Producao.Planos,Jan_2013,1202.482,2013,Jan,Producao,Planos
2,Producao.Longos,Jan_2013,848.959,2013,Jan,Producao,Longos
3,Producao.Placas,Jan_2013,394.660,2013,Jan,Producao,Placas
4,Producao.Blocos,Jan_2013,75.711,2013,Jan,Producao,Blocos
...,...,...,...,...,...,...,...
2249,Importacao.Planos,Fev_2021,133.079,2021,Fev,Importacao,Planos
2250,Importacao.Longos,Fev_2021,102.509,2021,Fev,Importacao,Longos
2251,Importacao.Semiacabados p/ Venda,Fev_2021,98.282,2021,Fev,Importacao,Semiacabados p/ Venda
2252,Caparente.Planos,Fev_2021,1237.750,2021,Fev,Caparente,Planos
2253,Caparente.Longos,Fev_2021,887.621,2021,Fev,Caparente,Longos

In [18]:
## Criando uma coluna para o trimestre 
dict_tri = {
    'Jan':1,
    'Fev':1,
    'Mar':1,
    'Abr':2,
    'Mai':2,
    'Jun':2,
    'Jul':3,
    'Ago':3,
    'Set':3,
    'Out':4,
    'Nov':4,
    'Dez':4,
}
df['trimestre'] = df['mes'].map(dict_tri)
df

,especificacao,periodo,quantidade,ano,mes,categoria,subcategoria,trimestre
0,Producao.Aco Bruto,Jan_2013,2769.437,2013,Jan,Producao,Aco Bruto,1
1,Producao.Planos,Jan_2013,1202.482,2013,Jan,Producao,Planos,1
2,Producao.Longos,Jan_2013,848.959,2013,Jan,Producao,Longos,1
3,Producao.Placas,Jan_2013,394.660,2013,Jan,Producao,Placas,1
4,Producao.Blocos,Jan_2013,75.711,2013,Jan,Producao,Blocos,1
...,...,...,...,...,...,...,...,...
2249,Importacao.Planos,Fev_2021,133.079,2021,Fev,Importacao,Planos,1
2250,Importacao.Longos,Fev_2021,102.509,2021,Fev,Importacao,Longos,1
2251,Importacao.Semiacabados p/ Venda,Fev_2021,98.282,2021,Fev,Importacao,Semiacabados p/ Venda,1
2252,Caparente.Planos,Fev_2021,1237.750,2021,Fev,Caparente,Planos,1
2253,Caparente.Longos,Fev_2021,887.621,2021,Fev,Caparente,Longos,1

In [23]:
## Reordenando as colunas
df = df[['especificacao', 'categoria', 'subcategoria','trimestre','periodo','ano','mes','quantidade']]
df

,especificacao,categoria,subcategoria,trimestre,periodo,ano,mes,quantidade
0,Producao.Aco Bruto,Producao,Aco Bruto,1,Jan_2013,2013,Jan,2769.437
1,Producao.Planos,Producao,Planos,1,Jan_2013,2013,Jan,1202.482
2,Producao.Longos,Producao,Longos,1,Jan_2013,2013,Jan,848.959
3,Producao.Placas,Producao,Placas,1,Jan_2013,2013,Jan,394.660
4,Producao.Blocos,Producao,Blocos,1,Jan_2013,2013,Jan,75.711
...,...,...,...,...,...,...,...,...
2249,Importacao.Planos,Importacao,Planos,1,Fev_2021,2021,Fev,133.079
2250,Importacao.Longos,Importacao,Longos,1,Fev_2021,2021,Fev,102.509
2251,Importacao.Semiacabados p/ Venda,Importacao,Semiacabados p/ Venda,1,Fev_2021,2021,Fev,98.282
2252,Caparente.Planos,Caparente,Planos,1,Fev_2021,2021,Fev,1237.750
2253,Caparente.Longos,Caparente,Longos,1,Fev_2021,2021,Fev,887.621

In [20]:
## Salvando o DataFrame 
df.to_csv('C:\\Users\\leshi\\Projeto_Gerdau\\Quantidade_subcategoria.csv', index=False)

In [29]:
## Criando o DataFrame para Importacao e Exportacao
df_imp = temp2.iloc[[31,32,38,39]]
df_imp.head()

,especificacao,Jan_2013,Fev_2013,Mar_2013,Abr_2013,Mai_2013,Jun_2013,Jul_2013,Ago_2013,Set_2013,...,Jun_2020,Jul_2020,Ago_2020,Set_2020,Out_2020,Nov_2020,Dez_2020,Jan_2021,Fev_2021,pct
32,Total (Mil t / Thousand Tonnes),932.857,815.327,718.571,817.359,607.623,542.961,468.416,582.285,632.668,...,1075.817,875.307,840.736,756.225,842.296,514.380,766.327,531.149,765.572,44.135073
33,(US$ Milhões / US$ Millions),573.500,509.969,474.159,539.518,507.626,386.179,345.875,440.298,416.662,...,478.601,392.279,380.447,379.417,416.419,298.544,434.077,314.156,522.292,66.252435
39,Total (Mil t / Thousand Tonnes),278.849,294.371,271.355,329.867,266.444,240.314,381.910,337.270,363.978,...,190.127,145.508,129.394,142.192,162.524,198.828,204.062,324.474,333.870,2.895764
40,(US$ Milhões / US$ Millions),369.978,311.089,322.156,373.559,342.873,354.886,434.529,391.814,368.161,...,181.871,168.354,150.392,170.771,163.881,194.721,204.669,288.068,293.092,1.744033

In [40]:
## Renomeando as linhas
row = ["Exportacao.Total(mil_t)", "Exportacao.milhoes(dolar)","Importacao.Total(mil_t)","Importacao.milhoes(dolar)"]
df_imp.loc[0:4,['especificacao']] = row
df_imp

,especificacao,Jan_2013,Fev_2013,Mar_2013,Abr_2013,Mai_2013,Jun_2013,Jul_2013,Ago_2013,Set_2013,...,Jun_2020,Jul_2020,Ago_2020,Set_2020,Out_2020,Nov_2020,Dez_2020,Jan_2021,Fev_2021,pct
32,Exportacao.Total(mil_t),932.857,815.327,718.571,817.359,607.623,542.961,468.416,582.285,632.668,...,1075.817,875.307,840.736,756.225,842.296,514.380,766.327,531.149,765.572,44.135073
33,Exportacao.milhoes(dolar),573.500,509.969,474.159,539.518,507.626,386.179,345.875,440.298,416.662,...,478.601,392.279,380.447,379.417,416.419,298.544,434.077,314.156,522.292,66.252435
39,Importacao.Total(mil_t),278.849,294.371,271.355,329.867,266.444,240.314,381.910,337.270,363.978,...,190.127,145.508,129.394,142.192,162.524,198.828,204.062,324.474,333.870,2.895764
40,Importacao.milhoes(dolar),369.978,311.089,322.156,373.559,342.873,354.886,434.529,391.814,368.161,...,181.871,168.354,150.392,170.771,163.881,194.721,204.669,288.068,293.092,1.744033

In [41]:
## Tranformando os dados do formato largo para o formato longo.
df_imp_exp = pd.melt(df_imp, id_vars=['especificacao'], value_vars=lista_ano)
df_imp_exp.rename(columns = {'variable':'periodo', 'value':'valor'}, inplace = True)
df_imp_exp

                 especificacao   periodo    valor
0      Exportacao.Total(mil_t)  Jan_2013  932.857
1    Exportacao.milhoes(dolar)  Jan_2013  573.500
2      Importacao.Total(mil_t)  Jan_2013  278.849
3    Importacao.milhoes(dolar)  Jan_2013  369.978
4      Exportacao.Total(mil_t)  Fev_2013  815.327
..                         ...       ...      ...
387  Importacao.milhoes(dolar)  Jan_2021  288.068
388    Exportacao.Total(mil_t)  Fev_2021  765.572
389  Exportacao.milhoes(dolar)  Fev_2021  522.292
390    Importacao.Total(mil_t)  Fev_2021  333.870
391  Importacao.milhoes(dolar)  Fev_2021  293.092

[392 rows x 3 columns]

In [42]:
##Criando uma coluna para ano, mês, categoria e subcategoria
mes = []
ano = []
categoria =[]
subcategoria = []
for per in df_imp_exp['periodo']:
    periodo = per.split('_')
    mes.append(periodo[0])
    ano.append(periodo[1])   
df_imp_exp['ano'] = ano
df_imp_exp['mes'] = mes
for cat in df_imp_exp['especificacao']:
    conjunto = cat.split('.')
    categoria.append(conjunto[0])
    subcategoria.append(conjunto[1])   
df_imp_exp['categoria'] = categoria
df_imp_exp['subcategoria'] = subcategoria
df_imp_exp

,especificacao,periodo,valor,ano,mes,categoria,subcategoria
0,Exportacao.Total(mil_t),Jan_2013,932.857,2013,Jan,Exportacao,Total(mil_t)
1,Exportacao.milhoes(dolar),Jan_2013,573.500,2013,Jan,Exportacao,milhoes(dolar)
2,Importacao.Total(mil_t),Jan_2013,278.849,2013,Jan,Importacao,Total(mil_t)
3,Importacao.milhoes(dolar),Jan_2013,369.978,2013,Jan,Importacao,milhoes(dolar)
4,Exportacao.Total(mil_t),Fev_2013,815.327,2013,Fev,Exportacao,Total(mil_t)
...,...,...,...,...,...,...,...
387,Importacao.milhoes(dolar),Jan_2021,288.068,2021,Jan,Importacao,milhoes(dolar)
388,Exportacao.Total(mil_t),Fev_2021,765.572,2021,Fev,Exportacao,Total(mil_t)
389,Exportacao.milhoes(dolar),Fev_2021,522.292,2021,Fev,Exportacao,milhoes(dolar)
390,Importacao.Total(mil_t),Fev_2021,333.870,2021,Fev,Importacao,Total(mil_t)
391,Importacao.milhoes(dolar),Fev_2021,293.092,2021,Fev,Importacao,milhoes(dolar)

In [72]:
## Criando uma coluna para o trimestre
dict_imp = {
    'Jan':1,
    'Fev':1,
    'Mar':1,
    'Abr':2,
    'Mai':2,
    'Jun':2,
    'Jul':3,
    'Ago':3,
    'Set':3,
    'Out':4,
    'Nov':4,
    'Dez':4
}
df_imp_exp['trimestre'] = df_imp_exp['mes'].map(dict_imp)

In [84]:
## Reordenando as colunas
df_imp_exp = df_imp_exp[['especificacao','categoria','subcategoria','trimestre','periodo','ano','mes','valor']]
df_imp_exp

,especificacao,categoria,subcategoria,trimestre,periodo,ano,mes,valor
0,Exportacao.Total(mil_t),Exportacao,Total(mil_t),1,Jan_2013,2013,Jan,932.857
1,Exportacao.milhoes(dolar),Exportacao,milhoes(dolar),1,Jan_2013,2013,Jan,573.500
2,Importacao.Total(mil_t),Importacao,Total(mil_t),1,Jan_2013,2013,Jan,278.849
3,Importacao.milhoes(dolar),Importacao,milhoes(dolar),1,Jan_2013,2013,Jan,369.978
4,Exportacao.Total(mil_t),Exportacao,Total(mil_t),1,Fev_2013,2013,Fev,815.327
...,...,...,...,...,...,...,...,...
387,Importacao.milhoes(dolar),Importacao,milhoes(dolar),1,Jan_2021,2021,Jan,288.068
388,Exportacao.Total(mil_t),Exportacao,Total(mil_t),1,Fev_2021,2021,Fev,765.572
389,Exportacao.milhoes(dolar),Exportacao,milhoes(dolar),1,Fev_2021,2021,Fev,522.292
390,Importacao.Total(mil_t),Importacao,Total(mil_t),1,Fev_2021,2021,Fev,333.870
391,Importacao.milhoes(dolar),Importacao,milhoes(dolar),1,Fev_2021,2021,Fev,293.092

In [85]:
## Salvando o DataFrame importação e exportação
df_imp_exp.to_csv('Importacao_exportacao.csv', index=False)